version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - mvn install
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd

artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/start.sh
  discard-paths: yes