spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true

cookie:
  domain: localhost

cors:
  origin: http://localhost:3000